'use strict';
(() => {
const normalize=v=>{const l=Math.hypot(...v)||1;return v.map(x=>x/l);},subtract=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
const rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255);
class Mesh {
 constructor(position=[0,0,0],yaw=0,size=1){this.data=[];this.position=position;this.yaw=yaw;this.size=size;}
 point(p){const c=Math.cos(this.yaw),s=Math.sin(this.yaw),k=this.size;return [this.position[0]+(p[0]*c+p[2]*s)*k,this.position[1]+p[1]*k,this.position[2]+(-p[0]*s+p[2]*c)*k];}
 triangle(a,b,c,color,emissive=false){a=this.point(a);b=this.point(b);c=this.point(c);const n=emissive?[0,3,0]:normalize(cross(subtract(b,a),subtract(c,a))),co=typeof color==='string'?rgb(color):color;for(const p of [a,b,c])this.data.push(...p,...n,...co);}
 box(x,y,z,w,h,d,col,emit=false){const v=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y+h,z-d/2],[x-w/2,y+h,z-d/2],[x-w/2,y,z+d/2],[x+w/2,y,z+d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];for(const f of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]]){this.triangle(v[f[0]],v[f[1]],v[f[2]],col,emit);this.triangle(v[f[0]],v[f[2]],v[f[3]],col,emit);}}
 ellipsoid(x,y,z,rx,ry,rz,col,emit=false,seg=18,rings=10){const p=(i,j)=>{const a=i/seg*Math.PI*2,b=j/rings*Math.PI;return [x+rx*Math.sin(b)*Math.cos(a),y+ry*Math.cos(b),z+rz*Math.sin(b)*Math.sin(a)];},co=rgb(col),cs=Math.cos(this.yaw),sn=Math.sin(this.yaw),vertex=v=>{const pos=this.point(v),n=normalize([(v[0]-x)/(rx*rx||1),(v[1]-y)/(ry*ry||1),(v[2]-z)/(rz*rz||1)]),normal=emit?[0,3,0]:[n[0]*cs+n[2]*sn,n[1],-n[0]*sn+n[2]*cs];this.data.push(...pos,...normal,...co);};for(let j=0;j<rings;j++)for(let i=0;i<seg;i++){for(const v of [p(i,j),p(i+1,j),p(i,j+1),p(i+1,j),p(i+1,j+1),p(i,j+1)])vertex(v);}}

 softLink(a,b,r,col){const n=normalize(subtract(b,a)),x=normalize(cross(n,Math.abs(n[1])>.9?[1,0,0]:[0,1,0])),y=cross(n,x),mid=a.map((v,i)=>(v+b[i])/2),length=Math.hypot(...subtract(b,a))/2+.06,co=rgb(col),cs=Math.cos(this.yaw),sn=Math.sin(this.yaw),p=(i,j)=>{const angle=i/12*6.283,theta=j/8*Math.PI;return {v:mid.map((v,k)=>v+n[k]*Math.cos(theta)*length+(x[k]*Math.cos(angle)+y[k]*Math.sin(angle))*Math.sin(theta)*r),n:normalize(n.map((v,k)=>v*Math.cos(theta)/length+(x[k]*Math.cos(angle)+y[k]*Math.sin(angle))*Math.sin(theta)/r))};},vertex=p=>{this.data.push(...this.point(p.v),p.n[0]*cs+p.n[2]*sn,p.n[1],-p.n[0]*sn+p.n[2]*cs,...co);};for(let j=0;j<8;j++)for(let i=0;i<12;i++)for(const v of [p(i,j),p(i+1,j),p(i,j+1),p(i+1,j),p(i+1,j+1),p(i,j+1)])vertex(v);}

 link(a,b,r,col,end=r,emit=false){const n=normalize(subtract(b,a)),x=normalize(cross(n,Math.abs(n[1])>.9?[1,0,0]:[0,1,0])),y=cross(n,x),p=(origin,radius,i)=>origin.map((v,k)=>v+radius*(x[k]*Math.cos(i/8*6.283)+y[k]*Math.sin(i/8*6.283)));for(let i=0;i<8;i++){const u=p(a,r,i),v=p(a,r,i+1),w=p(b,end,i),q=p(b,end,i+1);this.triangle(u,w,v,col,emit);this.triangle(v,w,q,col,emit);this.triangle(b,q,w,col,emit);}}
 disk(x,y,z,r,col){for(let i=0;i<40;i++){const a=i/40*6.283,b=(i+1)/40*6.283;this.triangle([x,y,z],[x+Math.cos(b)*r,y,z+Math.sin(b)*r],[x+Math.cos(a)*r,y,z+Math.sin(a)*r],col);}}
 ring(x,y,z,r,col){for(let i=0;i<24;i++){const a=i/24*6.283,b=(i+1)/24*6.283;this.link([x+Math.cos(a)*r,y,z+Math.sin(a)*r],[x+Math.cos(b)*r,y,z+Math.sin(b)*r],.035,col,.035,true);}}
}
function wings(m,c,t,moving){if(c.wings==='none')return;const size=c.wingSize,col=c.wingColor,accent=c.accentColor,flap=Math.sin(t*(moving?5:1.8))*(moving?.45:.16);for(const side of [-1,1]){const p=(x,y,z)=>[side*x*size,1.2+y*size+flap*x/2,z*size-.15],root=p(.35,0,0);
 if(['angel','phoenix'].includes(c.wings)){const joint=p(1,.8,-.1),tip=p(2.6,.5,-.3);m.softLink(root,joint,.2,col);m.softLink(joint,tip,.19,col);for(let i=0;i<8;i++){const u=i/7,start=p(.85+u*1.7,.78-u*.22,-.1),end=p(.65+u*2.2,.2-u*.9,-.55-u*.55);m.softLink(start,end,.17*(1-u*.3),i%3===0?accent:col);}}
 else if(['bat','dragon'].includes(c.wings)){const tips=[p(.7,.95,.1),p(1.8,1.1,-.15),p(2.7,.45,-.4),p(2.2,-.3,-1.05),p(1.1,-.35,-.95)];for(let i=0;i<tips.length-1;i++){const a=tips[i],b=tips[i+1],notch=a.map((v,k)=>(v+b[k])/2+(root[k]-(v+b[k])/2)*.27);m.triangle(root,a,notch,col);m.triangle(root,notch,b,col);m.link(root,a,.065,accent,.022);}m.link(root,tips.at(-1),.065,accent,.025);if(c.wings==='dragon')m.link(tips[2],p(2.9,.55,-.4),.09,accent,0);}
 else {for(const [x,y,z,rx,ry] of c.wings==='butterfly'?[[1.25,.6,0,.85,1],[1.1,-.3,-.15,.65,.55]]:[[1.15,.55,-.1,.48,1.2],[.95,-.3,-.3,.35,.65]]){m.ellipsoid(side*x*size,1.2+y*size+flap, z,rx*size,ry*size,.09,col);m.ellipsoid(side*x*size,1.2+y*size+flap,z+.09,rx*size*.48,ry*size*.5,.035,accent);}}
}}
function tail(m,c,t){const col=c.bodyColor,a=c.accentColor,k=c.tailSize,id=c.animal;let type=c.tail;if(type==='natural')type=['bunny','jackalope','chimerabunny','spiritbunny','bear'].includes(id)?'pom':['dragon','kirin','axolotl','otter'].includes(id)?'dragon':['cat','tiger','snowleopard','ferret','unicorn','pegasus','deer'].includes(id)?'long':'fluffy';
 if(type==='pom')m.ellipsoid(0,.85,-.82,.28*k,.28*k,.28*k,a);
 if(type==='fluffy'||type==='nine'){const count=type==='nine'?9:1;for(let i=0;i<count;i++){const angle=count===1?0:(i-4)*.24,x=Math.sin(angle)*1.7*k,z=-.8-Math.cos(angle)*1.05*k,y=.7+Math.sin(t*1.4+i)*.08+(count===1?0:(i%3)*.1);m.link([0,.75,-.55],[x,y,z],.25*k,col,.19*k);m.ellipsoid(x,y,z,.23*k,.26*k,.38*k,a);}}
 if(type==='long'||type==='dragon'){let prev=[0,.65,-.6];for(let i=1;i<=5;i++){const p=[Math.sin(t*1.8-i*.4)*.12*i,.65-i*.055,-.6-i*.28*k];m.link(prev,p,.2*(1-i/7)*k,col,.17*(1-i/7)*k);if(type==='dragon')m.link(p,[p[0],p[1]+.25*(1-i/7),p[2]],.1,a,0);prev=p;}}
}
function horns(m,c,headY){const a=c.accentColor,y=headY+.38;if(c.horns==='unicorn'||c.horns==='crystal'){m.link([0,y,.9],[0,y+.9,.97],.15,a,0,c.horns==='crystal');for(let i=0;i<4;i++)m.ring(0,y+i*.14,.91+i*.01,.13-i*.02,c.wingColor);}
 if(c.horns==='twin')for(const s of [-1,1])m.link([s*.3,y,.48],[s*.48,y+.7,.3],.13,a,0);
 if(c.horns==='curled')for(const s of [-1,1]){let prev=[s*.4,y,.45];for(let i=1;i<=9;i++){const angle=i/9*5.3,p=[s*(.45+.25*Math.sin(angle)),y+.22-.26*Math.cos(angle),.4];m.link(prev,p,.095-i*.007,a,.085-i*.007);prev=p;}}
 if(c.horns==='antlers')for(const s of [-1,1]){m.link([s*.27,y,.45],[s*.8,y+1.15,.1],.07,a,.035);for(let i=0;i<3;i++){const p=[s*(.4+i*.15),y+.25+i*.3,.4-i*.08];m.link(p,[s*(.78+i*.2),p[1]+.25,.4],.045,a,.015);}}
}
function details(m,c,headY){const a=c.accentColor,id=c.animal;
 if(c.pattern!=='none')for(const side of [-1,1])for(let i=0;i<6;i++){const z=-.5+i*.19,y=.94+Math.sin(i*2)*.15,x=side*.45;if(c.pattern==='spots')m.ellipsoid(x,y,z,.04,.1,.09,a,false,6,3);if(c.pattern==='stripes')m.link([x,y-.18,z],[x,y+.18,z+.07],.045,a,.035);if(c.pattern==='stars'){m.link([x,y-.09,z],[x,y+.09,z],.03,a,.03,true);m.link([x,y,z-.09],[x,y,z+.09],.03,a,.03,true);}if(c.pattern==='runes'){m.link([x,y-.09,z],[x,y+.1,z+.07],.025,a,.025,true);m.link([x,y+.1,z+.07],[x,y-.09,z+.13],.025,a,.025,true);}}
 if(c.accessory==='halo')m.ring(0,headY+1.05,.65,.6,'#ffdd83');
 if(c.accessory==='crown'){m.ring(0,headY+.45,.65,.42,'#e4bd6d');for(let i=0;i<5;i++){const angle=i/5*6.283;m.link([Math.cos(angle)*.4,headY+.45,.65+Math.sin(angle)*.4],[Math.cos(angle)*.4,headY+.8,.65+Math.sin(angle)*.4],.09,'#e4bd6d',0);}}
 if(c.accessory==='crystals')for(let i=0;i<4;i++)m.link([0,1.12,-.6+i*.25],[0,1.6,-.6+i*.25],.16,c.wingColor,0,true);
 if(c.accessory==='flowers')for(let i=0;i<7;i++){const angle=i/7*6.283;m.ellipsoid(Math.cos(angle)*.45,headY+.4,.65+Math.sin(angle)*.43,.12,.12,.12,c.wingColor);}
 if(c.accessory==='scarf'){m.ring(0,.98,.54,.43,c.wingColor);m.box(.25,.55,.72,.2,.5,.13,c.wingColor);}
 if(id==='axolotl')for(const side of [-1,1])for(let i=0;i<3;i++){const a=[side*.4,headY-.12+i*.15,.65];m.link(a,[side*(.9-i*.1),headY-.3+i*.3,.62],.07,c.accentColor,.025);}
}
function creature(config,{position=[0,0,0],yaw=0,t=0,moving=false}={}){const c=WildwoodModel.appearance(config),m=new Mesh(position,yaw,c.size),id=c.animal,col=c.bodyColor,a=c.accentColor,step=moving?Math.sin(t*12)*.13:0;
 const bird=['owl','phoenix','gryphon'].includes(id),pony=['unicorn','pegasus','deer','kirin'].includes(id),rabbit=['bunny','jackalope','chimerabunny'].includes(id),feline=['cat','tiger','snowleopard'].includes(id),long=['ferret','otter','axolotl'].includes(id),headY=pony?1.7:bird?1.6:1.35;
 if(id==='spiritbunny'){m.ellipsoid(0,.87,0,.65,.67,.75,col);m.ellipsoid(0,1.48,.53,.68,.58,.55,col);for(const side of [-1,1]){m.ellipsoid(side*.34,2.08,.48,.21,.64*c.earSize,.2,col);m.ellipsoid(side*.34,2.12,.66,.095,.45*c.earSize,.04,a);m.ellipsoid(side*.38,.28,.55,.27,.25,.35,col);m.ellipsoid(side*.4,.24,-.42,.27,.24,.3,col);m.ellipsoid(side*.3,1.59,1.025,.12,.15,.05,c.eyeColor,c.glowEyes);m.ellipsoid(side*.3-.035,1.645,1.073,.039,.046,.015,'#f5ffff',true);m.ellipsoid(side*.48,1.35,.96,.11,.055,.027,'#b4e5ef');}m.ellipsoid(0,1.33,1.08,.26,.17,.1,a);m.ellipsoid(0,1.39,1.177,.07,.05,.025,c.eyeColor);}

 else {
  m.ellipsoid(0,pony?1:.85,0,id==='bear'?.67:long?.37:.48,pony?.5:bird?.8:.5,long?1.05:.8,col);m.ellipsoid(0,headY,pony?.66:.64,pony?.47:bird?.65:.63,pony?.5:.58,pony?.4:.52,col);
  if(bird){if(id==='owl')for(const s of [-1,1])m.ellipsoid(s*.27,headY+.1,1.02,.25,.27,.08,a);m.link([0,headY-.1,1.06],[0,headY-.18,1.5],.19,'#e3b668',0);}
  else {m.ellipsoid(0,headY-.22,pony?1:1,.34,pony?.32:.24,pony?.4:.28,a);m.ellipsoid(0,headY-.12,pony?1.34:1.24,.1,.08,.07,'#354350');}
  for(const s of [-1,1]){const legY=pony?.72:.54;for(const front of [-1,1]){const z=front*.48;m.ellipsoid(s*.31,legY*.5+.16+step*s*front,z,pony?.14:.2,legY*.55,.21,col);m.ellipsoid(s*.31,.17+step*s*front,z+.1,pony?.18:.24,.17,pony?.23:.29,a);}m.ellipsoid(s*(pony?.23:.3),headY+.19,pony?1.02:1.125,.1,.125,.048,c.eyeColor,c.glowEyes);m.ellipsoid(s*(pony?.23:.3)-.018,headY+.23,pony?1.065:1.17,.03,.035,.014,'#fbffff',true);
   if(!bird)m.ellipsoid(s*.46,headY-.03,pony?.96:1.02,.085,.04,.025,'#eab9bd');
   if(rabbit||id==='bat'){m.ellipsoid(s*.28,headY+.72*c.earSize,.53,.17,.7*c.earSize,.17,col);m.ellipsoid(s*.28,headY+.77*c.earSize,.68,.08,.48*c.earSize,.03,a);}
   else if(id==='bear'||id==='otter'){m.ellipsoid(s*.44,headY+.4,.5,.2*c.earSize,.2*c.earSize,.13,col);}
   else if(!bird&&id!=='axolotl'){m.ellipsoid(s*.35,headY+.45*c.earSize,.5,.23*c.earSize,.36*c.earSize,.17,col);m.ellipsoid(s*.35,headY+.48*c.earSize,.655,.105*c.earSize,.2*c.earSize,.025,a);}
  }
  if(pony){for(let i=0;i<6;i++)m.ellipsoid(0,1.35+i*.1,.05+i*.05,.15,.2,.13,c.wingColor);}
 }
 tail(m,c,t);wings(m,c,t,moving);horns(m,c,headY);details(m,c,headY);
 return new Float32Array(m.data);
}
function soul(type,position,t,eye=[4,3,6]){const s=WildwoodModel.souls.find(x=>x.id===type);if(!s)return {solid:new Float32Array(),glow:new Float32Array()};const m=new Mesh(position),g=new Mesh(),color=s.color,co=rgb(color);m.ellipsoid(0,0,0,.19,.22,.19,color,true);m.ellipsoid(0,-.03,.02,.095,.14,.1,'#f5ffff',true);for(let i=0;i<5;i++){const a=t*1.7+i/5*6.283,x=Math.cos(a)*.11,z=Math.sin(a)*.11;m.link([x,-.06,z],[x*.5+Math.sin(t*4+i)*.04,.36+Math.sin(t*3+i)*.08,z*.5],.09,color,0,true);}
 const normal=normalize(subtract(eye,position)),right=normalize(cross([0,1,0],normal)),up=cross(normal,right),p=(r,a)=>position.map((v,k)=>v+r*(right[k]*Math.cos(a)+up[k]*Math.sin(a)));
 for(const [inner,outer,bright1,bright2] of [[0,.28,.55,.32],[.28,.55,.32,.08],[.55,.9,.08,0]])for(let i=0;i<24;i++){const a=i/24*6.283,b=(i+1)/24*6.283,v=[p(inner,a),p(outer,a),p(outer,b),p(inner,b)],colors=[bright1,bright2,bright2,bright1];for(const face of [[0,1,2],[0,2,3]])for(const j of face)g.data.push(...v[j],0,3,0,...co.map(c=>c*colors[j]));}
 for(let i=0;i<5;i++){const phase=(t*.7+i*.2)%1,angle=t+i*1.7,px=Math.sin(angle)*.27*phase,pz=Math.cos(angle)*.27*phase;m.ellipsoid(px,.3+phase*.65,pz,.025*(1-phase),.04*(1-phase),.025*(1-phase),color,true,5,3);}
 return {solid:new Float32Array(m.data),glow:new Float32Array(g.data)};
}
function glow(position,color,eye,radius=1,intensity=.3){const data=[],co=rgb(color),n=normalize(subtract(eye,position)),right=normalize(cross([0,1,0],n)),up=cross(n,right),point=(r,a)=>position.map((v,k)=>v+r*(right[k]*Math.cos(a)+up[k]*Math.sin(a)));for(const [inner,outer,a,b] of [[0,radius*.35,1,.3],[radius*.35,radius,.3,0]])for(let i=0;i<20;i++){const angle=i/20*6.283,next=(i+1)/20*6.283,v=[point(inner,angle),point(outer,angle),point(outer,next),point(inner,next)],brightness=[a,b,b,a];for(const f of [[0,1,2],[0,2,3]])for(const j of f)data.push(...v[j],0,3,0,...co.map(x=>x*brightness[j]*intensity));}return new Float32Array(data);}
function multiply(a,b){const c=new Float32Array(16);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)c[i*4+j]+=a[k*4+j]*b[i*4+k];return c;}
class Preview {
 constructor(canvas,getConfig){this.canvas=canvas;this.getConfig=getConfig;this.yaw=.65;this.pitch=.2;this.zoom=8.5;this.drag=null;this.disposed=false;const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('3D preview unavailable');this.gl=gl;const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p,n,c;uniform mat4 vp;varying vec3 color;void main(){gl_Position=vp*vec4(p,1.);color=c*(length(n)>2.?1.:(.64+.36*max(dot(normalize(n),normalize(vec3(-.4,1.,.8))),0.)));}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 color;void main(){gl_FragColor=vec4(color,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));this.program=program;gl.useProgram(program);this.loc={p:gl.getAttribLocation(program,'p'),n:gl.getAttribLocation(program,'n'),c:gl.getAttribLocation(program,'c'),vp:gl.getUniformLocation(program,'vp')};this.buffer=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.clearColor(.055,.105,.14,1);
 canvas.addEventListener('pointerdown',e=>{this.drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!this.drag)return;this.yaw-=(e.clientX-this.drag[0])*.012;this.pitch=Math.max(-.15,Math.min(.8,this.pitch+(e.clientY-this.drag[1])*.006));this.drag=[e.clientX,e.clientY];});canvas.addEventListener('pointerup',()=>this.drag=null);canvas.addEventListener('pointercancel',()=>this.drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(5,Math.min(13,this.zoom+e.deltaY*.008));},{passive:false});
 this.tick=time=>{if(this.disposed)return;this.draw(time/1000);this.frame=requestAnimationFrame(this.tick);};this.frame=requestAnimationFrame(this.tick);
 }
 draw(t){const gl=this.gl,c=this.canvas,d=Math.min(devicePixelRatio||1,1.5);const w=Math.round(c.clientWidth*d),h=Math.round(c.clientHeight*d);if(w<1||h<1)return;if(c.width!==w||c.height!==h){c.width=w;c.height=h;}gl.viewport(0,0,w,h);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const config=this.getConfig(),distance=this.zoom*(config.wings!=="none"?1.22:1)*Math.max(1,config.size)*Math.max(1,config.wingSize*.8),yaw=this.yaw,eye=[Math.sin(yaw)*distance,2+Math.sin(this.pitch)*distance,Math.cos(yaw)*distance],target=[0,1.3,0],z=normalize(subtract(eye,target)),x=normalize(cross([0,1,0],z)),y=cross(z,x),f=1/Math.tan(.72/2),near=.1,far=50,view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]),projection=new Float32Array([f/(w/h),0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);gl.uniformMatrix4fv(this.loc.vp,false,multiply(projection,view));const pedestal=new Mesh();pedestal.disk(0,.01,0,2.35,'#1d3841');pedestal.ring(0,.02,0,2.3,'#668779');pedestal.ring(0,.03,0,1.8,'#3d6762');this.render(new Float32Array(pedestal.data));this.render(creature(config,{yaw:Math.sin(t*.12)*.15,t}));const orb=soul(config.soul,[1.4,1.55+Math.sin(t*2)*.12,.45],t,eye);this.render(orb.solid);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);gl.depthMask(false);this.render(orb.glow);gl.depthMask(true);gl.disable(gl.BLEND);this.error=gl.getError();}
 render(data){if(!data.length)return;const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);for(const [k,offset] of [['p',0],['n',12],['c',24]]){gl.enableVertexAttribArray(this.loc[k]);gl.vertexAttribPointer(this.loc[k],3,gl.FLOAT,false,36,offset);}gl.drawArrays(gl.TRIANGLES,0,data.length/9);}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.gl.deleteBuffer(this.buffer);this.gl.deleteProgram(this.program);const extension=this.gl.getExtension('WEBGL_lose_context');if(extension)extension.loseContext();}
}
window.MythicMesh={Mesh,creature,soul,glow,Preview};
})();
