'use strict';
(() => {
const M=WildwoodModel,pretty=s=>s==='none'?'None':s[0].toUpperCase()+s.slice(1);
class CharacterCreator {
 constructor(container,state,{onSave,required=false}){
  this.container=container;this.draft={...M.appearance(state),name:state.name};this.onSave=onSave;this.required=required;this.tab='Creature';
  container.innerHTML=`<div class="creator-layout"><div class="creator-stage"><div class="stage-stars" aria-hidden="true">✦ <span>✧</span> · <b>✦</b></div><div class="preview-badge">LIVE 3D PREVIEW</div><canvas id="character-preview" aria-label="Interactive 3D preview of your mythical animal"></canvas><div class="preview-caption"><h3 id="preview-species"></h3><p id="preview-description"></p><span id="preview-soul"></span></div><div class="preview-controls"><span>Drag to rotate · scroll to zoom</span><button id="reset-preview" aria-label="Reset preview camera">↺</button></div></div><div class="creator-options"><div class="creator-name"><label for="name-input">YOUR ANIMAL’S NAME</label><input id="name-input" maxlength="24" autocomplete="off"></div><div class="creator-tabs" role="tablist" aria-label="Character options">${['Creature','Colors','Wings','Details','Soul'].map((s,i)=>`<button role="tab" id="creator-tab-${i}" data-tab="${s}" aria-controls="creator-pane">${s}${s==='Soul'?'<span class="soul-dot"></span>':''}</button>`).join('')}</div><div id="creator-pane" class="creator-pane" role="tabpanel"></div><div class="creator-toolbar"><button id="random-look">✦ Surprise me</button><button id="export-look">Export look</button><button id="import-look">Import look</button><input type="file" id="look-file" accept=".json,application/json" hidden></div></div></div><div class="creator-footer"><div><strong id="creator-bond"></strong><small id="creator-message" role="status" aria-live="polite"></small></div><button class="primary" id="done-custom">Save & explore <span>→</span></button></div>`;
  this.$=id=>container.querySelector('#'+id);this.$('name-input').value=this.draft.name;
  this.$('name-input').addEventListener('input',()=>this.draft.name=this.$('name-input').value);
  container.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.renderPane();});
  container.querySelector('.creator-tabs').addEventListener('keydown',e=>{const buttons=[...container.querySelectorAll('[data-tab]')],i=buttons.indexOf(document.activeElement);if(i<0)return;if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].click();buttons[next].focus();}});
  try{this.preview=new MythicMesh.Preview(this.$('character-preview'),()=>this.draft);}catch(e){this.$('preview-description').textContent=e.message;}
  this.$('reset-preview').onclick=()=>{if(this.preview){this.preview.yaw=.65;this.preview.pitch=.2;this.preview.zoom=8.5;}};
  this.$('random-look').onclick=()=>{this.draft={...M.randomLook(),name:this.draft.name};this.renderPane();};
  this.$('done-custom').onclick=()=>{if(!this.draft.soul)return;this.onSave({...M.appearance(this.draft),name:this.draft.name.trim()||'Mythic explorer'});};
  this.$('export-look').onclick=()=>{const blob=new Blob([JSON.stringify({format:'wildwood-look',version:1,name:this.draft.name,...M.appearance(this.draft)},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='wildwood-character.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.message('Character look exported.');};
  this.$('import-look').onclick=()=>this.$('look-file').click();
  this.$('look-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000)throw Error('That file is too large for a character look.');const data=JSON.parse(await file.text());if(data.format!=='wildwood-look'||data.version!==1)throw Error('Choose a Wildwood character JSON file.');this.draft={...M.appearance(data),name:typeof data.name==='string'?data.name.slice(0,24):this.draft.name};this.$('name-input').value=this.draft.name;this.renderPane();this.message('Look imported. Choose a soul if needed, then save.');}catch(error){this.message(error.message);}e.target.value='';};
  this.renderPane();
 }
 message(s){this.$('creator-message').textContent=s;}
 update(){const animal=M.species.find(a=>a.id===this.draft.animal),soul=M.souls.find(s=>s.id===this.draft.soul);this.$('preview-species').textContent=animal.name;this.$('preview-description').textContent=animal.description;this.$('preview-soul').textContent=soul?'✦ '+soul.name+' soul · bonded':'✧ Your soul awaits';this.$('preview-soul').style.color=soul?soul.color:'#d5d9e8';this.$('creator-bond').textContent=soul?soul.name+' soul chosen':'Choose your soul';this.$('creator-message').textContent=soul?'Your animal and soul will explore together.':'Open the Soul tab and choose your glowing companion.';this.$('done-custom').disabled=!soul;
  this.container.querySelectorAll('[data-animal]').forEach(b=>{const selected=b.dataset.animal===this.draft.animal;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});
  this.container.querySelectorAll('[data-soul]').forEach(b=>{const selected=b.dataset.soul===this.draft.soul;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});
  this.container.querySelectorAll('[data-wings]').forEach(b=>{const selected=b.dataset.wings===this.draft.wings;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});
 }
 range(key,label){return `<label class="range-label" for="look-${key}">${label}<output id="value-${key}">${this.draft[key].toFixed(2)}×</output></label><input id="look-${key}" data-range="${key}" type="range" min=".65" max="1.7" step=".01" value="${this.draft[key]}">`;}
 select(key,label){return `<label for="look-${key}">${label}</label><select id="look-${key}" data-select="${key}">${M.choices[key].map(v=>`<option value="${v}" ${v===this.draft[key]?'selected':''}>${pretty(v)}</option>`).join('')}</select>`;}
 renderPane(){const pane=this.$('creator-pane');this.container.querySelectorAll('[data-tab]').forEach(b=>{const selected=b.dataset.tab===this.tab;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1;});pane.setAttribute('aria-labelledby','creator-tab-'+['Creature','Colors','Wings','Details','Soul'].indexOf(this.tab));
  if(this.tab==='Creature')pane.innerHTML=`<div class="pane-heading"><h3>Find your wild side</h3><span>24 creatures</span></div><p class="pane-intro">Start with a creature, then make it entirely yours.</p><div class="species-grid">${M.species.map(a=>`<button data-animal="${a.id}" title="${a.description}"><span class="species-icon" style="--species-color:${a.color}">${a.icon}</span><strong>${a.name}</strong></button>`).join('')}</div>`;
  if(this.tab==='Colors')pane.innerHTML=`<div class="pane-heading"><h3>Paint a little magic</h3><span>Any color</span></div><p class="pane-intro">Mix your own colors. There is no palette limit.</p><div class="color-fields">${[['bodyColor','Fur / scales'],['accentColor','Markings / details'],['eyeColor','Eyes'],['wingColor','Wings / adornments']].map(([k,label])=>`<label for="look-${k}"><span>${label}<small id="hex-${k}">${this.draft[k].toUpperCase()}</small></span><input type="color" id="look-${k}" data-color-field="${k}" value="${this.draft[k]}" aria-label="${label} color"></label>`).join('')}</div><label>Quick fur colors</label><div class="swatches">${[...M.palette,'#6bcce8','#ebc8df','#ede5d3','#8a78b8','#507f87','#dc8283','#1e3343'].map((c,i)=>`<button class="swatch" data-color="${i}" data-hex="${c}" style="background:${c}" aria-label="Fur color ${c}"></button>`).join('')}</div><label class="check-label"><input id="glow-eyes" type="checkbox" ${this.draft.glowEyes?'checked':''}> Starlight eyes</label>${this.select('pattern','Fur / scale pattern')}`;
  if(this.tab==='Wings')pane.innerHTML=`<div class="pane-heading"><h3>Give dreams wings</h3><span>Mix with any creature</span></div><p class="pane-intro">Feathers, moonlit membranes, or a little fairy magic.</p><div class="wing-grid">${[['none','No wings','○'],['angel','Angel wings','🪽'],['bat','Bat wings','🦇'],['fairy','Fairy wings','✧'],['butterfly','Butterfly wings','🦋'],['dragon','Dragon wings','🐉'],['phoenix','Phoenix wings','🔥']].map(([id,name,icon])=>`<button data-wings="${id}"><span>${icon}</span><strong>${name}</strong></button>`).join('')}</div>${this.range('wingSize','Wingspan')}<p class="pane-note">Wing color is yours to choose in Colors.</p>`;
  if(this.tab==='Details')pane.innerHTML=`<div class="pane-heading"><h3>Make a myth</h3><span>Mix & match</span></div><div class="detail-selects">${this.select('horns','Horns & antlers')}${this.select('tail','Tail style')}${this.select('accessory','Adornments')}</div>${this.range('size','Body size')}${this.range('earSize','Ear size')}${this.range('tailSize','Tail length / fluff')}`;
  if(this.tab==='Soul')pane.innerHTML=`<div class="pane-heading"><h3>What kind of soul are you?</h3><span>Choose your bond</span></div><p class="pane-intro">A little orb of living fire. Your light follows you wherever you wander.</p><div class="soul-grid">${M.souls.map(s=>`<button data-soul="${s.id}" style="--soul-color:${s.color}"><span class="soul-flame" aria-hidden="true"></span><div><strong>${s.name}</strong><small>${s.description}</small></div></button>`).join('')}</div>`;
  pane.querySelectorAll('[data-animal]').forEach(b=>b.onclick=()=>{const soul=this.draft.soul;this.draft={...M.preset(b.dataset.animal),soul,name:this.draft.name};this.update();});
  pane.querySelectorAll('[data-soul]').forEach(b=>b.onclick=()=>{this.draft.soul=b.dataset.soul;this.update();});
  pane.querySelectorAll('[data-wings]').forEach(b=>b.onclick=()=>{this.draft.wings=b.dataset.wings;this.update();});
  pane.querySelectorAll('[data-range]').forEach(input=>input.oninput=()=>{this.draft[input.dataset.range]=Number(input.value);this.$('value-'+input.dataset.range).textContent=Number(input.value).toFixed(2)+'×';});
  pane.querySelectorAll('[data-select]').forEach(input=>input.onchange=()=>{this.draft[input.dataset.select]=input.value;this.update();});
  pane.querySelectorAll('[data-color-field]').forEach(input=>input.oninput=()=>{this.draft[input.dataset.colorField]=input.value;this.$('hex-'+input.dataset.colorField).textContent=input.value.toUpperCase();});
  pane.querySelectorAll('[data-hex]').forEach(b=>b.onclick=()=>{this.draft.bodyColor=b.dataset.hex;this.$('look-bodyColor').value=b.dataset.hex;this.$('hex-bodyColor').textContent=b.dataset.hex.toUpperCase();});
  if(this.$('glow-eyes'))this.$('glow-eyes').onchange=e=>this.draft.glowEyes=e.target.checked;
  this.update();
 }
 diagnostics(){return {draft:{...this.draft},required:this.required,tab:this.tab,previewError:this.preview?.error??null};}
 dispose(){this.preview?.dispose();}
}
window.CharacterCreator=CharacterCreator;
})();
