'use strict';
(() => {
const $=id=>document.getElementById(id),M=WildwoodModel,canvas=$('world');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
function fail(text){$('error').hidden=false;$('error').textContent=text;document.body.dataset.ready='error';}
if(!gl){fail('WebGL could not start. Open this game in Edge or Chrome with graphics acceleration enabled.');return;}
let state=M.fresh(),saveAvailable=true;
try{state=M.validate(JSON.parse(localStorage.getItem('wildwood-save-v1')));}catch(e){saveAvailable=false;}
function save(){try{localStorage.setItem('wildwood-save-v1',JSON.stringify(state));saveAvailable=true;}catch(e){saveAvailable=false;document.querySelector('.status').textContent='Offline · saving unavailable';}}
const vs='attribute vec3 p,n,c;uniform mat4 vp;uniform vec3 eye,lightColor,sunDirection,lanternPosition;uniform float ambient,diffuse,lanternStrength;varying vec3 color;varying float dist;void main(){gl_Position=vp*vec4(p,1.);bool glow=length(n)>2.;float light=ambient+diffuse*max(dot(normalize(n),normalize(sunDirection)),0.);float warm=pow(max(0.,1.-distance(p,lanternPosition)/5.),2.)*lanternStrength;color=glow?c:c*(light*lightColor+vec3(1.,.63,.25)*warm);dist=glow?0.:distance(p,eye);}';
const fs='precision mediump float;uniform vec3 sky;uniform vec2 fogRange;uniform float opacity;varying vec3 color;varying float dist;void main(){gl_FragColor=vec4(mix(color,sky,smoothstep(fogRange.x,fogRange.y,dist)*.8),opacity);}';

function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
const program=gl.createProgram();try{gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));}catch(e){fail('Renderer error: '+e.message);return;}
gl.useProgram(program);gl.enable(gl.DEPTH_TEST);gl.clearColor(.67,.82,.82,1);
const loc={};for(const k of ['p','n','c'])loc[k]=gl.getAttribLocation(program,k);for(const k of ['vp','eye','lightColor','sunDirection','ambient','diffuse','sky','fogRange','opacity','lanternPosition','lanternStrength'])loc[k]=gl.getUniformLocation(program,k);
const norm=v=>{const l=Math.hypot(...v)||1;return v.map(x=>x/l);},sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255);
let geometry=[],transform=null;
function point(v){if(!transform)return v;const [x,y,z,a]=transform,c=Math.cos(a),s=Math.sin(a);return [x+v[0]*c+v[2]*s,y+v[1],z-v[0]*s+v[2]*c];}
function tri(a,b,c,color){a=point(a);b=point(b);c=point(c);const n=norm(cross(sub(b,a),sub(c,a))),co=rgb(color);for(const p of [a,b,c])geometry.push(...p,...n,...co);}
function box(x,y,z,w,h,d,col){const v=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y+h,z-d/2],[x-w/2,y+h,z-d/2],[x-w/2,y,z+d/2],[x+w/2,y,z+d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];for(const f of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]]){tri(v[f[0]],v[f[1]],v[f[2]],col);tri(v[f[0]],v[f[2]],v[f[3]],col);}}
function cone(x,y,z,r,h,col,segments=9,top=0){for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,b=(i+1)/segments*Math.PI*2,p=[x+Math.cos(a)*r,y,z+Math.sin(a)*r],q=[x+Math.cos(b)*r,y,z+Math.sin(b)*r],u=[x+Math.cos(a)*top,y+h,z+Math.sin(a)*top],v=[x+Math.cos(b)*top,y+h,z+Math.sin(b)*top];tri(p,u,q,col);if(top)tri(q,u,v,col);tri([x,y+h,z],v,u,col);}}
function ellipsoid(x,y,z,rx,ry,rz,col,seg=9,rings=5){const pt=(i,j)=>{const a=i/seg*Math.PI*2,b=j/rings*Math.PI;return [x+rx*Math.sin(b)*Math.cos(a),y+ry*Math.cos(b),z+rz*Math.sin(b)*Math.sin(a)];};for(let j=0;j<rings;j++)for(let i=0;i<seg;i++){tri(pt(i,j),pt(i+1,j),pt(i,j+1),col);tri(pt(i+1,j),pt(i+1,j+1),pt(i,j+1),col);}}
function disk(x,y,z,r,col,n=48){for(let i=0;i<n;i++){const a=i/n*6.283,b=(i+1)/n*6.283;tri([x,y,z],[x+Math.cos(b)*r,y,z+Math.sin(b)*r],[x+Math.cos(a)*r,y,z+Math.sin(a)*r],col);}}
const obstacles=[],ambience=new CottageAmbience(),runes=new RunestoneGarden();
function tree(x,z,size=1,type=0){cone(x,0,z,.25*size,2.4*size,'#886f4f',7,.18*size);if(type){cone(x,1.6*size,z,1.8*size,3*size,'#6b9776');cone(x,3*size,z,1.3*size,2.3*size,'#7ba986');}else{ellipsoid(x,3*size,z,1.8*size,1.8*size,1.8*size,'#87a66a');ellipsoid(x+.8*size,3.2*size,z-.3*size,1.2*size,1.4*size,1.2*size,'#a3b875');}obstacles.push({x,z,r:.32*size});}
function hut(x,z,color){cone(x,0,z,2.7,3,'#f2d7a0',10,2.7);cone(x,3,z,3.4,2.6,color,10);box(x,0,z+2.64,1.25,2.05,.13,'#6f7957');box(x,1,z+2.75,.3,.15,.12,'#eec37b');for(const a of [-1,1])box(x+a*1.9,1.35,z+1.97,.65,.65,.12,'#91b5ad');obstacles.push({x,z,r:2.8});}
let seed=81237;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
disk(0,-.4,0,250,'#83bbc4',80);cone(0,-.35,0,43,.35,'#e9d9aa',80,42);disk(0,.005,0,40.5,'#a9bd7b',80);
for(let i=-29;i<30;i+=1.6){disk(i,.025,Math.sin(i*.08)*2,2.2,'#d7cd9e',12);disk(0,.03,i,1.8,'#d7cd9e',12);}
disk(0,.04,0,6,'#e1d6af',32);disk(-20,.02,-12,7,'#bfd198',30);disk(20,.02,-17,8,'#bed08c',30);disk(15,.045,5,5,'#e2d8ac',24);disk(15,.05,5,4.3,'#72b5be',24);
append(ambience.staticMesh());append(runes.staticMesh());for(const s of runes.stones)obstacles.push({x:s.x,z:s.z,r:.8});obstacles.push({x:-8,z:15.2,r:3.25},{x:-8,z:10.3,r:6.5});hut(8,-8,'#c19575');box(-8,.03,19,3,.15,1.7,'#a89264');
disk(-8,.04,23,5,'#d6ca9f',24);disk(-8,.06,23,2.8,'#c68977',24);disk(-8,.075,23,2.4,'#ecc298',24);box(-11,.05,24,1.4,.6,2,'#ae8669');box(-11,.65,24,1.3,.18,1.9,'#e5c7a1');box(-5,.05,22,1.5,.8,1.5,'#a98662');cone(-5,.86,22,.6,.7,'#95ac72',9,.4);
for(let i=0;i<70;i++){const x=(rand()-.5)*78,z=(rand()-.5)*78;if(runes.stones.some(s=>Math.hypot(s.x-x,s.z-z)<2.5)||Math.hypot(x,z)>37||Math.abs(x)<4||Math.abs(z-Math.sin(x*.08)*2)<4||Math.hypot(x+8,z-26)<14||Math.hypot(x-15,z-5)<7||Math.hypot(x-20,z+17)<5||M.landmarkPoints.some(p=>Math.hypot(p[0]-x,p[1]-z)<2))continue;tree(x,z,.7+rand()*.65,i%3===0);}
for(let i=0;i<45;i++){const a=rand()*6.283,r=33+rand()*7;ellipsoid(Math.cos(a)*r,.3,Math.sin(a)*r,.5+rand()*.9,.5+rand()*.6,.6,'#a3ada0',7,4);}
for(let i=0;i<170;i++){const x=(rand()-.5)*72,z=(rand()-.5)*72;if(Math.hypot(x,z)>35||Math.abs(x)<3||Math.abs(z)<3||Math.hypot(x-15,z-5)<5)continue;cone(x,.03,z,.07,.33,'#7f9b62',4);ellipsoid(x,.37,z,.17,.12,.17,['#efcb86','#e4a496','#dcd6bb'][i%3],5,3);}
for(let i=0;i<7;i++){const a=i/7*6.283;ellipsoid(20+Math.cos(a)*3,.6,-17+Math.sin(a)*3,.6,.8,.6,'#b0b7a0',7,4);}cone(20,0,-17,1.1,.7,'#a6b693',8,.9);cone(20,.7,-17,.7,1.5,'#afc785',6,.12);
for(const p of [[-63,-55,12],[60,-60,16],[-70,12,10],[70,30,12]])cone(p[0],-.3,p[1],p[2],5,'#aac4b0',12,3);
const staticData=new Float32Array(geometry),staticBuffer=gl.createBuffer(),dynamicBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,staticBuffer);gl.bufferData(gl.ARRAY_BUFFER,staticData,gl.STATIC_DRAW);
function bind(buffer){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);for(const [name,offset] of [['p',0],['n',12],['c',24]]){gl.enableVertexAttribArray(loc[name]);gl.vertexAttribPointer(loc[name],3,gl.FLOAT,false,36,offset);}}
const npcs=[{x:2,z:0,name:'Pip · your island guide',kind:'bunny',color:'#c3b6a0'},{x:-20,z:-12,name:'Sage · grove keeper',kind:'owl',color:'#a68c74'}];
const labels=npcs.map(n=>{const d=document.createElement('div');d.className='label';d.textContent=n.name;$('labels').appendChild(d);return {d,x:n.x,y:3,z:n.z};});

function multiply(a,b){const c=new Float32Array(16);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)c[i*4+j]+=a[k*4+j]*b[i*4+k];return c;}
let vp,eye,cameraYaw=.45,cameraPitch=.49,zoom=15,keys=new Set(),drag=null,jumpY=0,jumpV=0,moving=false,modalOpen=false,lastTime=0,elapsed=0,lastSave=0,near=null,toastTime=0,sound=true,audio=null,characterEditor=null,creatorRequired=false,soulPosition=null;
try{sound=localStorage.getItem("wildwood-music-v1")!=="off";}catch(e){}
function musicLabel(){$("sound").textContent="Music: "+(sound?"on":"off");$("sound").setAttribute("aria-pressed",sound);}
function audioFailure(){sound=false;musicLabel();$("sound").textContent="Music unavailable";}
function startMusic(){if(!sound||document.hidden)return;try{audio=audio||new WoodlandScore(new(window.AudioContext||window.webkitAudioContext)());audio.start().catch(audioFailure);}catch(e){audioFailure();}}
function toggleMusic(){sound=!sound;musicLabel();try{localStorage.setItem("wildwood-music-v1",sound?"on":"off");}catch(e){}if(sound)startMusic();else if(audio)audio.pause().catch(audioFailure);}
musicLabel();
canvas.addEventListener("pointerdown",startMusic);
document.addEventListener("visibilitychange",()=>{if(!audio)return;if(document.hidden)audio.pause().catch(audioFailure);else if(sound)audio.resume().catch(audioFailure);});
addEventListener("pagehide",()=>{if(audio)audio.pause().catch(()=>{});});
function camera(){eye=[state.x+Math.sin(cameraYaw)*Math.cos(cameraPitch)*zoom,1.1+Math.sin(cameraPitch)*zoom,state.z+Math.cos(cameraYaw)*Math.cos(cameraPitch)*zoom];const z=norm(sub(eye,[state.x,1,state.z])),x=norm(cross([0,1,0],z)),y=cross(z,x);const view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]),f=1/Math.tan(.75/2),n=.1,far=250,projection=new Float32Array([f/(canvas.width/canvas.height),0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);vp=multiply(projection,view);gl.uniformMatrix4fv(loc.vp,false,vp);gl.uniform3fv(loc.eye,eye);}
function project(x,y,z){const w=vp[3]*x+vp[7]*y+vp[11]*z+vp[15];return {x:(1+(vp[0]*x+vp[4]*y+vp[8]*z+vp[12])/w)*innerWidth/2,y:(1-(vp[1]*x+vp[5]*y+vp[9]*z+vp[13])/w)*innerHeight/2,w};}
function resize(){const d=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);gl.viewport(0,0,canvas.width,canvas.height);}addEventListener('resize',resize);resize();
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastTime=elapsed+3.5;}
function chime(){if(sound&&audio)audio.chime();}
function refresh(){const a=M.species.find(a=>a.id===state.animal),s=M.souls.find(s=>s.id===state.soul);$('animal-name').textContent=state.name||'Mythic explorer';$('portrait').textContent=a.icon;$('level').textContent=s?s.name+' soul · '+a.name:'Choose your soul';}

const map=$('map').getContext('2d');function minimap(){map.fillStyle='#88b8bc';map.fillRect(0,0,180,180);map.fillStyle='#bdcd96';map.beginPath();map.arc(90,90,82,0,7);map.fill();map.strokeStyle='#e4d8b3';map.lineWidth=6;map.beginPath();map.moveTo(30,90);map.lineTo(150,90);map.moveTo(90,30);map.lineTo(90,150);map.stroke();map.fillStyle='#75aeb9';map.beginPath();map.arc(120,100,9,0,7);map.fill();for(const p of [[-8,23,'#ad8164'],[-20,-12,'#6f8560'],[20,-17,'#738f60']]){map.fillStyle=p[2];map.fillRect(87+p[0]*2,87+p[1]*2,6,6);}for(const r of runes.stones){map.fillStyle='#799d9c';map.beginPath();map.arc(90+r.x*2,90+r.z*2,2.4,0,6.283);map.fill();}map.save();map.translate(90+state.x*2,90+state.z*2);map.rotate(-state.yaw);map.fillStyle='#365c45';map.strokeStyle='#fff9ec';map.lineWidth=2;map.beginPath();map.moveTo(0,7);map.lineTo(-5,-5);map.lineTo(5,-5);map.closePath();map.fill();map.stroke();map.restore();}
function openModal(kicker,title,html){keys.clear();modalOpen=true;const d=$('modal').querySelector('.dialog');d.classList.remove('creator-dialog','sky-dialog');$('close-modal').disabled=false;$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-content').innerHTML=html;$('modal').hidden=false;$('close-modal').focus();}
function closeModal(force=false){if(creatorRequired&&!state.soul&&force!==true)return;characterEditor?.dispose();characterEditor=null;creatorRequired=false;modalOpen=false;$('modal').hidden=true;$('modal').querySelector('.dialog').classList.remove('creator-dialog','sky-dialog');$('close-modal').disabled=false;keys.clear();save();canvas.focus();}$('close-modal').onclick=()=>closeModal();

document.addEventListener('keydown',e=>{if(!modalOpen||e.key!=='Tab')return;const items=[...$('modal').querySelectorAll('button,input')].filter(x=>!x.disabled),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
function welcome(){openModal('AN ANIMAL JAM–INSPIRED SANDBOX','A world of your own.',`<p>Welcome to Wildwood, a little world for mythical animals. Create a plushy creature, choose a glowing soul, and explore at your own pace.</p><p>Every look and decoration is yours. Shape the time of day and weather, meet your neighbors, and make your garden bloom.</p><div class="key-row"><span>Move / look around</span><span>WASD / drag</span></div><div class="key-row"><span>Jump / interact</span><span>Space / E</span></div><div class="key-row"><span>Create / skies</span><span>C / T</span></div><button class="primary" id="begin">Create my character</button>`);$('begin').onclick=()=>{startMusic();closeModal(true);customize();};}

function help(){openModal('EXPLORER’S GUIDE','Follow your curiosity.',`<div class="key-row"><span>Move / run</span><span>WASD or arrows / Shift</span></div><div class="key-row"><span>Camera / zoom</span><span>Drag the world / scroll</span></div><div class="key-row"><span>Jump / interact</span><span>Space / E</span></div><div class="key-row"><span>Character / home / skies</span><span>C / H / T</span></div><div class="key-row"><span>Pause / mute music</span><span>Escape / M</span></div><p>Your island is a sandbox. Every creature, wing style, and decoration is free to use. The brown map square is your den; green squares mark the grove and shrine.</p><p>Character, soul, garden, and sky settings save automatically on this device.</p><button class="primary" id="continue">Back to the island</button>`);$('continue').onclick=()=>closeModal();}

function customize(){creatorRequired=!state.soul;openModal('THE MYTHIC CHARACTER ATELIER','Dream up your wild side.', '');$('modal').querySelector('.dialog').classList.add('creator-dialog');$('close-modal').disabled=creatorRequired;characterEditor=new CharacterCreator($('modal-content'),state,{required:creatorRequired,onSave:look=>{Object.assign(state,look);state.started=true;refresh();save();soulPosition=null;closeModal(true);toast('Your creature and '+M.souls.find(s=>s.id===state.soul).name+' soul are ready.');}});$('name-input').focus();}

function goHome(){cameraYaw=0;cameraPitch=.36;zoom=18;state.x=-8;state.z=23;jumpY=jumpV=0;state.yaw=Math.PI;save();soulPosition=null;toast('Home sweet den. Press E to decorate freely.');}
function skies(){openModal('YOUR SKY, YOUR STORY','Set the mood.', '');$('modal').querySelector('.dialog').classList.add('sky-dialog');weather.mount($('modal-content'));$('sky-done').onclick=()=>closeModal();}
function interact(){if(!near)return;if(near.kind==='runestone'){openModal('WORDS IN THE MOSS',near.title,`<div class="rune-sign" aria-hidden="true">ᚱ · ᛉ · ᚨ</div><p class="rune-poem" id="rune-poem"></p><button class="primary" id="rune-close">Back to the forest</button>`);$('rune-poem').textContent=near.poem;$('rune-close').onclick=()=>closeModal();return;}if(near==='den'){const planted=state.visited.includes('den');openModal('YOUR PERSONAL DEN','A little room to grow.',`<p>Make this garden your quiet corner of the island. Add a ring of flowers around your rug whenever you like.</p><button class="primary" id="plant">${planted?'Clear the flower garden':'Plant a flower garden'}</button><button class="primary secondary" id="den-back">Back to exploring</button>`);$('plant').onclick=()=>{if(state.visited.includes('den'))state.visited=state.visited.filter(x=>x!=='den');else state.visited.push('den');closeModal();toast(state.visited.includes('den')?'Your den is blooming!':'A fresh space for your next idea.');};$('den-back').onclick=()=>closeModal();return;}const title=near==='shrine'?'A little wonder.':near.name.startsWith('Sage')?'Hello, curious one.':'Welcome, little explorer!';const text=near==='shrine'?'The meadow’s shrine glows with quiet magic. Sit with your soul, watch the skies, and make this moment your own.':near.name.startsWith('Sage')?'Every creature belongs in this grove. Choose a snowy midnight, a soft sunrise, or a little rain. There is no hurry here.':'I’m Pip. This island is your sandbox! Create any creature with C, shape the skies with T, and return to your garden with H. Your glowing soul will stay close.';openModal(near==='shrine'?'SUNPETAL MEADOW':near.name,title,`<p>${text}</p><button class="primary" id="talk-done">Keep exploring</button><button class="primary secondary" id="talk-skies">Shape the skies</button>`);$('talk-done').onclick=()=>closeModal();$('talk-skies').onclick=skies;}

$('help').onclick=help;$('wardrobe').onclick=customize;$('home').onclick=goHome;$('pause').onclick=()=>{save();openModal('TAKE YOUR TIME','Island paused.',`<p>Your island will be here when you’re ready.</p><button class="primary" id="resume">Resume exploring</button>`);$('resume').onclick=closeModal;};$('sound').onclick=toggleMusic;$('world-settings').onclick=skies;
addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(modalOpen)closeModal();else $('pause').click();return;}if(modalOpen)return;startMusic();const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k===' '&&jumpY===0)jumpV=6;if(k==='e')interact();if(k==='c')customize();if(k==='h')goHome();if(k==='m')toggleMusic();if(k==='t')skies();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();drag=null;save();});document.addEventListener('visibilitychange',()=>{keys.clear();lastTime=0;save();});addEventListener('pagehide',save);
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||modalOpen)return;cameraYaw-=(e.clientX-drag.x)*.006;cameraPitch=Math.max(.2,Math.min(1.15,cameraPitch+(e.clientY-drag.y)*.004));drag={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(8,Math.min(27,zoom+e.deltaY*.015));},{passive:false});
function update(dt){if(modalOpen){moving=false;return;}let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dz=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));dx+=window.WildwoodTouch?.x||0;dz+=window.WildwoodTouch?.z||0;moving=!!(dx||dz);if(moving){const l=Math.hypot(dx,dz),speed=(keys.has('shift')?8:5)*dt*(water.contains(state.x,state.z)&&jumpY<water.depth?.65:1);dx/=l;dz/=l;const wx=(dx*Math.cos(cameraYaw)+dz*Math.sin(cameraYaw))*speed,wz=(-dx*Math.sin(cameraYaw)+dz*Math.cos(cameraYaw))*speed;state.yaw=Math.atan2(wx,wz);M.move(state,wx,0,obstacles);M.move(state,0,wz,obstacles);}if(jumpY>0||jumpV>0){jumpY=Math.max(0,jumpY+jumpV*dt-8*dt*dt);jumpV-=16*dt;if(jumpY===0)jumpV=0;}near=null;for(const n of npcs)if(Math.hypot(state.x-n.x,state.z-n.z)<3)near=n;if(Math.hypot(state.x-20,state.z+17)<3)near='shrine';if(Math.hypot(state.x+8,state.z-23)<4)near='den';const stone=runes.nearest(state.x,state.z);if(stone)near={...stone,kind:'runestone'};$('interaction').hidden=!near;if(near)$('interaction').querySelector('span').textContent=near==='shrine'?'Discover the shrine':near==='den'?'Decorate your den':near.kind==='runestone'?'Read '+near.title:'Talk to '+near.name.split(' ·')[0];let place='SUNLIT COMMONS',desc='A good day to wander.';if(state.x<-12&&state.z<0){place='FERNWOOD GROVE';desc='A little wisdom among the trees.';}else if(state.x>12&&state.z<-7){place='SUNPETAL MEADOW';desc='Follow the flowers. Find a little wonder.';}else if(state.z>16&&state.x<0){place='YOUR GARDEN DEN';desc='A place to call your own.';}$('place-name').textContent=place;$('place-description').textContent=desc;if(elapsed-lastSave>3){save();lastSave=elapsed;}}
function append(data){for(let i=0;i<data.length;i++)geometry.push(data[i]);}
const weather=new WeatherCycle(()=>state),water=new ShallowWater();
function draw(t){const env=weather.environment;gl.clearColor(...env.sky,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);camera();gl.uniform3fv(loc.sky,env.sky);gl.uniform2fv(loc.fogRange,env.fog);gl.uniform3fv(loc.lightColor,env.light);gl.uniform3fv(loc.sunDirection,env.sunDirection);gl.uniform1f(loc.ambient,env.ambient);gl.uniform1f(loc.diffuse,env.diffuse);gl.uniform1f(loc.opacity,1);gl.uniform3fv(loc.lanternPosition,ambience.lantern);gl.uniform1f(loc.lanternStrength,.12+(1-env.day)*.9);bind(staticBuffer);gl.drawArrays(gl.TRIANGLES,0,staticData.length/9);geometry=[];disk(state.x,.08,state.z,.85*state.size,'#8c9f69',20);append(weather.geometry([state.x,0,state.z]));append(MythicMesh.creature(state,{position:[state.x,jumpY,state.z],yaw:state.yaw,t,moving}));for(const n of npcs)append(MythicMesh.creature({...M.preset(n.kind),bodyColor:n.color,wings:'none'},{position:[n.x,0,n.z],yaw:.5,t}));if(state.visited.includes('den'))for(let i=0;i<16;i++){const a=i/16*6.283,x=-8+Math.cos(a)*3.5,z=23+Math.sin(a)*3.5;cone(x,.1,z,.08,.5,'#749466',4);ellipsoid(x,.65,z,.3,.2,.3,['#dfaa95','#e7c779','#b8a5cb'][i%3],6,3);}
const target=[state.x+Math.cos(state.yaw)*1.25-Math.sin(state.yaw)*.7,1.6+jumpY*.6+Math.sin(t*2)*.12,state.z-Math.sin(state.yaw)*1.25-Math.cos(state.yaw)*.7];if(!soulPosition||Math.hypot(soulPosition[0]-target[0],soulPosition[2]-target[2])>15)soulPosition=[...target];else soulPosition=soulPosition.map((v,i)=>v+(target[i]-v)*.08);const orb=MythicMesh.soul(state.soul,soulPosition,t,eye);append(orb.solid);append(water.particles());const cottage=ambience.dynamic(t,env.day,eye),runeLight=runes.dynamic(env.day,eye);append(cottage.solid);append(runeLight.solid);bind(dynamicBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(geometry),gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,geometry.length/9);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.uniform1f(loc.opacity,.8);const waterMesh=water.surface();gl.bufferData(gl.ARRAY_BUFFER,waterMesh,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,waterMesh.length/9);gl.uniform1f(loc.opacity,.3);const smoke=ambience.smoke(t,env.day);gl.bufferData(gl.ARRAY_BUFFER,smoke,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,smoke.length/9);gl.uniform1f(loc.opacity,1);gl.depthMask(true);gl.disable(gl.BLEND);if(orb.glow.length){gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);gl.depthMask(false);gl.bufferData(gl.ARRAY_BUFFER,orb.glow,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,orb.glow.length/9);gl.bufferData(gl.ARRAY_BUFFER,cottage.glow,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,cottage.glow.length/9);gl.bufferData(gl.ARRAY_BUFFER,runeLight.glow,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,runeLight.glow.length/9);gl.depthMask(true);gl.disable(gl.BLEND);}for(const l of labels){const p=project(l.x,l.y,l.z);l.d.style.display=p.w>0&&Math.hypot(state.x-l.x,state.z-l.z)<24?'block':'none';l.d.style.left=p.x+'px';l.d.style.top=p.y+'px';}minimap();}

function frame(time){const dt=lastTime?Math.min((time-lastTime)/1000,.1):0;lastTime=time;elapsed+=dt;weather.update(dt,!modalOpen);update(dt);water.update(dt,{x:state.x,z:state.z,jumpY,moving,yaw:state.yaw,size:state.size},!modalOpen);draw(elapsed);if(elapsed>toastTime)$('toast').classList.remove('show');requestAnimationFrame(frame);}
refresh();if(!saveAvailable)document.querySelector('.status').textContent='Offline · saving unavailable';if(!state.started)welcome();else if(!state.soul)customize();requestAnimationFrame(frame);document.body.dataset.ready='true';window.WildwoodDiagnostics=()=>({ready:true,webgl:gl.getError(),vertices:staticData.length/9,state:JSON.parse(JSON.stringify(state)),saveAvailable,creator:characterEditor?characterEditor.diagnostics():null,soulPosition,jump:{height:jumpY,velocity:jumpV},runestones:runes.stones.length,ambience:{night:Math.max(0,1-weather.environment.day*1.7),fireflies:weather.environment.day<.58?32:0,flowers:ambience.flowers.length,lantern:ambience.lantern},water:water.diagnostics(),weather:weather.diagnostics(),music:{enabled:sound,...(audio?audio.diagnostics():{started:false,title:"Fernlight"})}});
})();

