'use strict';
(() => {
const names={clear:'Clear skies',cloudy:'Cloudy',rain:'Rain',snow:'Snow',mist:'Mist'},mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
class WeatherCycle {
 constructor(getState){this.getState=getState;this.elapsed=0;this.canvas=document.getElementById('weather-effects');this.ctx=this.canvas.getContext('2d');this.current=getState().world.weather==='auto'?getState().world.autoWeather:getState().world.weather;this.weights={clear:0,cloudy:0,rain:0,snow:0,mist:0};this.weights[this.current]=1;this.autoIndex=['clear','cloudy','rain','mist','clear','snow'].indexOf(this.current);this.particles=Array.from({length:WildwoodPerformance.mobile?90:150},(_,i)=>({x:(i*.6180339887)%1,y:(i*.41421356)%1,s:.5+(i*.73205)%1}));this.stars=Array.from({length:65},(_,i)=>{const a=i*2.399,r=45+(i*13%35);return [Math.cos(a)*r,22+(i*7%60),Math.sin(a)*r];});this.update(0,false);}
 update(dt,advance=true){const w=this.getState().world;this.elapsed+=dt;if(advance){if(w.cycle)w.hour=(w.hour+dt*24/600*w.speed)%24;if(w.weather==='auto'){w.weatherAge+=dt;if(w.weatherAge>=85){const sequence=['clear','cloudy','rain','mist','clear','snow'];this.autoIndex=(this.autoIndex+1)%sequence.length;w.autoWeather=sequence[this.autoIndex];w.weatherAge=0;}}}this.current=w.weather==='auto'?w.autoWeather:w.weather;const amount=1-Math.exp(-dt*.7);for(const key of Object.keys(this.weights))this.weights[key]+=(Number(key===this.current)-this.weights[key])*amount;
  const sun=Math.sin((w.hour-6)*Math.PI/12),day=clamp((sun+.16)/.9),twilight=clamp(1-Math.abs(sun)*5),cover=clamp(this.weights.cloudy*.55+this.weights.rain*.8+this.weights.snow*.6+this.weights.mist*.7);let sky=mix([.035,.07,.135],[.67,.82,.86],day);sky=mix(sky,[.78,.57,.49],twilight*.5*(1-cover));sky=mix(sky,day>.3?[.49,.61,.66]:[.075,.11,.17],cover);const warm=twilight*(1-cover);this.environment={sky,day,ambient:.24+day*.43,diffuse:.2+day*.15,light:mix([.59,.7,1],[1,.99,.91],day).map((v,i)=>i===2?v-warm*.18:v),sunDirection:sun>-.1?[-.4,Math.max(.12,sun),.5]:[.25,Math.max(.12,-sun),-.4],fog:[40-cover*19,115-cover*49]};
  const minutes=Math.floor(w.hour*60)%1440,h=Math.floor(minutes/60).toString().padStart(2,'0'),m=(minutes%60).toString().padStart(2,'0');document.getElementById('clock-time').textContent=h+':'+m;document.getElementById('weather-name').textContent=names[this.current]+(w.weather==='auto'?' · auto':'');document.getElementById('day-marker').style.left=w.hour/24*100+'%';this.precipitation(dt);
 }
 precipitation(dt){const c=this.canvas,ctx=this.ctx,d=Math.min(devicePixelRatio||1,WildwoodPerformance.mobile?1:1.5),w=innerWidth,h=innerHeight;if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);}ctx.clearRect(0,0,w,h);const rain=this.weights.rain,snow=this.weights.snow;if(rain<.01&&snow<.01)return;
  for(const p of this.particles){p.y=(p.y+dt*(rain>.3?.75:.035)*p.s)%1;const x=(p.x*w+Math.sin(this.elapsed*.7+p.s*7)*(snow>.2?14:2)+this.elapsed*(rain>.3?30:5))%(w+40)-20,y=p.y*h;if(rain>.01){ctx.strokeStyle=`rgba(193,222,239,${rain*(.18+p.s*.14)})`;ctx.lineWidth=.7+p.s*.45;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+3,y+10+p.s*9);ctx.stroke();}if(snow>.01){ctx.fillStyle=`rgba(246,252,255,${snow*(.4+p.s*.3)})`;ctx.beginPath();ctx.arc(x,y,1.1+p.s*1.6,0,6.283);ctx.fill();}}
 }
 geometry(position){const Mesh=MythicMesh.Mesh,m=new Mesh(),w=this.getState().world,t=this.elapsed,day=this.environment.day,phase=(w.hour-6)*Math.PI/12;const sun=[position[0]-28,Math.sin(phase)*65,position[2]+Math.cos(phase)*65],moon=[position[0]+25,-Math.sin(phase)*65,position[2]-Math.cos(phase)*65];if(sun[1]>-5)m.ellipsoid(...sun,3.2,3.2,3.2,'#ffefb3',true,18,10);if(moon[1]>-5){m.ellipsoid(...moon,2.1,2.1,2.1,'#dcecff',true,18,10);for(let i=0;i<4;i++)m.ellipsoid(moon[0]+Math.sin(i*3)*.8,moon[1]+Math.cos(i*2)*.6,moon[2]+1.8,.25,.18,.05,'#bbd0eb',true,7,4);}
  if(day<.45)for(const p of this.stars){const co=[.76,.86,1].map(v=>v*(1-day/.45));const q=[position[0]+p[0],p[1],position[2]+p[2]];m.triangle([q[0]-.13,q[1],q[2]],[q[0]+.13,q[1],q[2]],[q[0],q[1]+.24,q[2]],co,true);}
  const cloud=this.weights.cloudy+this.weights.rain+this.weights.snow+this.weights.mist*.4;const col=this.current==='rain'?'#899ea7':day>.4?'#d8e3e0':'#344758';for(let i=0;i<Math.ceil(3+cloud*5);i++){const x=position[0]+((i*27+t*.55)%100)-50,z=position[2]-35+(i*23%60),y=18+i%3*3;for(let j=0;j<3;j++)m.ellipsoid(x+j*2.5,y+(j%2)*.7,z,3.8,1.5,2.7,col,false,9,5);}
  return new Float32Array(m.data);
 }
 mount(container){const w=this.getState().world;container.innerHTML=`<p class="weather-intro">A sunrise for exploring, a snowy night for dreaming. The sky is yours.</p><div class="sky-presets"><button data-time="6">🌅<span>Dawn</span></button><button data-time="12">☀<span>Noon</span></button><button data-time="18">🌇<span>Dusk</span></button><button data-time="0">☾<span>Midnight</span></button></div><label class="range-label" for="world-hour">Time of day <output id="hour-output"></output></label><input id="world-hour" type="range" min="0" max="23.99" step=".01" value="${w.hour}"><label class="check-label"><input type="checkbox" id="world-cycle" ${w.cycle?'checked':''}> Let day turn into night</label><label class="range-label" for="world-speed">Day cycle speed <output id="speed-output">${w.speed}×</output></label><input id="world-speed" type="range" min=".25" max="4" step=".25" value="${w.speed}"><label>Weather</label><div class="weather-grid">${[['auto','✦','Changing skies'],['clear','☀','Clear'],['cloudy','☁','Cloudy'],['rain','☂','Rain'],['snow','❄','Snow'],['mist','≋','Mist']].map(([id,icon,name])=>`<button data-weather="${id}"><span>${icon}</span>${name}</button>`).join('')}</div><p class="weather-note">Changing skies gently moves between weather types. A normal day takes about ten minutes.</p><button class="primary" id="sky-done">Back to my island</button>`;
  const $=id=>container.querySelector('#'+id),refresh=()=>{const hour=this.getState().world.hour;this.update(0,false);$('world-hour').value=hour;$('hour-output').textContent=document.getElementById('clock-time').textContent;container.querySelectorAll('[data-weather]').forEach(b=>{const selected=b.dataset.weather===w.weather;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});};container.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{w.hour=Number(b.dataset.time);refresh();});$('world-hour').oninput=e=>{w.hour=Number(e.target.value);refresh();};$('world-cycle').onchange=e=>w.cycle=e.target.checked;$('world-speed').oninput=e=>{w.speed=Number(e.target.value);$('speed-output').textContent=w.speed+'×';};container.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{w.weather=b.dataset.weather;refresh();});refresh();
 }
 diagnostics(){return {hour:this.getState().world.hour,weather:this.current,setting:this.getState().world.weather,weights:{...this.weights},daylight:this.environment.day};}
}
window.WeatherCycle=WeatherCycle;
})();
