const {spawn}=require('node:child_process'),fs=require('node:fs');
const root=process.env.WILDWOOD_ROOT||'D:/AnimalJamOffline/android-build/mobile-test';
const child=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--no-first-run','--remote-debugging-port=9225','--user-data-dir='+root+'/touch-profile','--use-angle=swiftshader','--enable-unsafe-swiftshader','about:blank'],{windowsHide:true,stdio:'ignore'});
let ws,id=0;const pending=new Map(),errors=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function call(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});}
async function ev(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
function assert(v,m){if(!v)throw Error(m);}
async function touch(type,x,y){return call('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y,id:1}]});}
async function point(selector){return ev(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);}
(async()=>{
 let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:9225/json')).json();if(tabs.length)break;}catch{}await sleep(150);}assert(tabs?.length,'Browser startup');ws=new WebSocket(tabs[0].webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:800,height:400,deviceScaleFactor:1,mobile:true});await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await call('Page.navigate',{url:'file:///'+root+'/game/index.html'});for(let i=0;i<60;i++){if(await ev('document.body?.dataset.ready==="true"'))break;await sleep(250);}assert(await ev('document.body?.dataset.ready==="true"'),'Startup failed: '+await ev('document.body?.innerText'));
 const save={...require('../game/model.js').fresh(),started:true,soul:'frost'};const hook=await call('Page.addScriptToEvaluateOnNewDocument',{source:'localStorage.setItem("wildwood-save-v1",'+JSON.stringify(JSON.stringify(save))+')'});await call('Page.reload');for(let i=0;i<60;i++){if(await ev('document.body?.dataset.ready==="true"'))break;await sleep(250);}await call('Page.removeScriptToEvaluateOnNewDocument',{identifier:hook.identifier});
 assert(await ev(`getComputedStyle(document.getElementById('mobile-controls')).display==='flex'`),'Touch controls hidden');const before=await ev('WildwoodDiagnostics().state');let p=await point('#touch-stick');await touch('touchStart',p.x,p.y);await touch('touchMove',p.x+40,p.y);await sleep(800);const after=await ev('WildwoodDiagnostics().state');assert(Math.hypot(after.x-before.x,after.z-before.z)>1,'Joystick movement failed');await touch('touchEnd');assert(await ev('WildwoodTouch.x===0&&WildwoodTouch.z===0'),'Joystick release stuck');
 p=await point('[data-key=" "]');await touch('touchStart',p.x,p.y);await sleep(100);assert((await ev('WildwoodDiagnostics().jump')).height>0,'Touch jump failed');await touch('touchEnd');await sleep(700);
 await ev('document.getElementById("wardrobe").click()');await sleep(300);assert(await ev('document.getElementById("mobile-controls").hidden'),'Controls visible under modal');let shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(root+'/mobile-creator.png',Buffer.from(shot.data,'base64'));assert(await ev(`document.querySelector('.creator-layout').getBoundingClientRect().width<innerWidth`),'Creator exceeds mobile viewport');await ev('document.getElementById("close-modal").click()');await sleep(300);assert(await ev('!document.getElementById("mobile-controls").hidden'),'Touch controls not restored');
 p=await point('#touch-skies');await touch('touchStart',p.x,p.y);await touch('touchEnd');await sleep(200);assert(await ev('!!document.getElementById("sky-done")'),'Touch sky menu failed');await ev('document.getElementById("sky-done").click()');await sleep(300);shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(root+'/mobile-game.png',Buffer.from(shot.data,'base64'));assert(!errors.length,'Browser exception '+JSON.stringify(errors));assert((await ev('WildwoodDiagnostics()')).webgl===0,'WebGL error');console.log('PASS: landscape touch movement, release, jump, creator layout, modal isolation, sky menu, WebGL');await call('Browser.close');ws.close();
})().catch(async e=>{console.error(e);try{await call('Browser.close');}catch{}child.kill();process.exitCode=1;});
