const {spawn}=require('node:child_process'),fs=require('node:fs'),M=require('../game/model.js');
const root=process.env.WILDWOOD_ROOT||'D:/AnimalJamOffline/android-build/mobile-test';
const child=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--no-first-run','--remote-debugging-port=9226','--user-data-dir='+root+'/bobo-profile','--use-angle=swiftshader','--enable-unsafe-swiftshader','--window-size=1280,800','about:blank'],{windowsHide:true,stdio:'ignore'});
let ws,id=0;const pending=new Map(),errors=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));function assert(v,m){if(!v)throw Error(m);}
function call(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});}
async function ev(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function shot(name){const r=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(root+'/'+name,Buffer.from(r.data,'base64'));}
(async()=>{let tabs;for(let i=0;i<80;i++){try{tabs=await(await fetch('http://127.0.0.1:9226/json')).json();if(tabs.length)break;}catch{}await sleep(150);}assert(tabs?.length,'Browser startup');ws=new WebSocket(tabs[0].webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};await call('Runtime.enable');await call('Page.enable');

const save={...M.fresh(),x:-18,z:-12,started:true,soul:'frost',world:{hour:10,cycle:false,speed:1,weather:'clear'}};await call('Page.addScriptToEvaluateOnNewDocument',{source:'localStorage.setItem("wildwood-save-v1",'+JSON.stringify(JSON.stringify(save))+')'});await call('Page.navigate',{url:'file:///'+root+'/game/index.html'});for(let i=0;i<80;i++){if(await ev('document.body?.dataset.ready==="true"'))break;await sleep(250);}assert(await ev('document.body?.dataset.ready==="true"'),'Startup failed');await sleep(2000);const d=await ev('WildwoodDiagnostics().foliage');console.log('Forest',d);assert(d.trees>=55&&d.shrubs>=100&&d.minHeight>5.9,'Forest density/height');assert(d.fallingLeaves>0&&d.fallingLeaves<=d.leafLimit,'Falling leaf pool');
assert(await ev('(()=>{const f=new WoodlandFoliage();f.tree(0,0,1);for(let i=0;i<600;i++)f.update(.1,{x:0,z:0},"rain");const before=f.time;f.update(.1,{x:0,z:0},"clear",false);return f.time===before&&f.wind>1.4&&f.leaves.some(p=>p.rest>0)&&f.leaves.every(p=>!p.active||(Number.isFinite(p.x)&&p.y>=0&&Number.isFinite(p.z)))&&Array.from(f.fallingMesh()).every(Number.isFinite)})()'),'Wind, settling, pause, finite geometry');await shot('forest-wind.png');assert(!errors.length,'Browser errors');assert((await ev('WildwoodDiagnostics()')).webgl===0,'WebGL error');console.log('PASS: dense tall forest, bounded falling leaves, rain breeze, settling and pause');await call('Browser.close');ws.close();})().catch(async e=>{console.error(e);try{await call('Browser.close');}catch{}child.kill();process.exitCode=1;});
