const {spawn}=require('node:child_process'),fs=require('node:fs'),M=require('../game/model.js');
const root=process.env.WILDWOOD_ROOT||'D:/AnimalJamOffline';
const child=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--autoplay-policy=no-user-gesture-required','--no-first-run','--no-default-browser-check','--remote-debugging-port=9224','--user-data-dir='+root+'/test-profile','--use-angle=swiftshader','--enable-unsafe-swiftshader','--window-size=1440,900','about:blank'],{windowsHide:true,stdio:'ignore'});
let socket,id=0;const pending=new Map(),errors=[],external=[],checks=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function assert(v,message){if(!v)throw Error(message);}
function call(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});socket.send(JSON.stringify({id:n,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function reload(s){const hook=await call('Page.addScriptToEvaluateOnNewDocument',{source:'localStorage.setItem("wildwood-save-v1",'+JSON.stringify(JSON.stringify(s))+')'});await call('Page.reload');await sleep(1000);await call('Page.removeScriptToEvaluateOnNewDocument',{identifier:hook.identifier});}
async function key(k,ms=0){await call('Input.dispatchKeyEvent',{type:'keyDown',key:k,code:k===' '?'Space':'Key'+k.toUpperCase(),windowsVirtualKeyCode:k===' '?32:k.toUpperCase().charCodeAt(0)});await sleep(ms||80);await call('Input.dispatchKeyEvent',{type:'keyUp',key:k,code:k===' '?'Space':'Key'+k.toUpperCase()});}
async function screenshot(name){const r=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(root+'/'+name,Buffer.from(r.data,'base64'));}
(async()=>{
 let tabs;for(let i=0;i<80;i++){try{tabs=await(await fetch('http://127.0.0.1:9224/json')).json();if(tabs.length)break;}catch{}await sleep(150);}assert(tabs?.length,'Edge did not start');socket=new WebSocket(tabs[0].webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p.reject(Error(JSON.stringify(m.error)));else p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Network.requestWillBeSent'&&/^https?:/.test(m.params.request.url))external.push(m.params.request.url);};await call('Runtime.enable');await call('Network.enable');await call('Page.enable');await call('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await call('Page.navigate',{url:'file:///'+root+'/game/index.html'});await sleep(1800);console.log('Startup',await evaluate('({ready:document.body.dataset.ready,error:document.getElementById("error").textContent})'),errors);assert(await evaluate('document.body.dataset.ready')==='true','Startup failed');
 await reload(M.fresh());await evaluate('document.getElementById("begin").click()');await sleep(600);assert(await evaluate('document.getElementById("done-custom").disabled&&document.getElementById("close-modal").disabled'),'Soul choice was not required');checks.push('Required soul selection');
 const geometry=await evaluate('WildwoodModel.species.map(a=>{const d=MythicMesh.creature({...WildwoodModel.preset(a.id),soul:"ember"});return {animal:a.id,vertices:d.length/9,valid:Array.from(d).every(Number.isFinite)};})');assert(geometry.length===24&&geometry.every(x=>x.vertices>500&&x.valid),'Creature geometry invalid');checks.push('24 complete creature meshes');
 await evaluate('document.querySelector("[data-animal=spiritbunny]").click();document.getElementById("name-input").value="Mochi";document.getElementById("name-input").dispatchEvent(new Event("input"));document.querySelector("[data-tab=Wings]").click();document.querySelector("[data-wings=angel]").click();document.querySelector("[data-tab=Colors]").click();document.getElementById("look-bodyColor").value="#64ccea";document.getElementById("look-bodyColor").dispatchEvent(new Event("input"));document.querySelector("[data-tab=Details]").click();document.getElementById("look-accessory").value="halo";document.getElementById("look-accessory").dispatchEvent(new Event("change"));document.querySelector("[data-tab=Soul]").click();document.querySelector("[data-soul=frost]").click()');await sleep(500);let d=await evaluate('WildwoodDiagnostics()');assert(d.creator.draft.wings==='angel'&&d.creator.draft.bodyColor==='#64ccea'&&d.creator.previewError===0,'Creator preview/customization failed');await screenshot('character-creator.png');await evaluate('document.getElementById("done-custom").click()');await call('Page.reload');await sleep(1000);d=await evaluate('WildwoodDiagnostics()');assert(d.state.animal==='spiritbunny'&&d.state.name==='Mochi'&&d.state.wings==='angel'&&d.state.soul==='frost'&&d.state.accessory==='halo'&&!d.creator,'Character save did not persist');checks.push('Live preview and appearance persistence');
 let before=d.state;const oldOrb=d.soulPosition;await key('w',700);d=await evaluate('WildwoodDiagnostics()');assert(Math.hypot(d.state.x-before.x,d.state.z-before.z)>.25,'Movement failed');assert(Math.hypot(d.soulPosition[0]-oldOrb[0],d.soulPosition[2]-oldOrb[2])>.2,'Soul did not follow');checks.push('Soul follows moving character');
 await evaluate('document.getElementById("wardrobe").click();document.querySelector("[data-tab=Wings]").click();document.querySelector("[data-wings=bat]").click()');await sleep(400);assert((await evaluate('WildwoodDiagnostics()')).creator.draft.wings==='bat','Bat wings failed');await screenshot('bat-wings.png');await evaluate('document.getElementById("close-modal").click()');assert((await evaluate('WildwoodDiagnostics()')).state.wings==='angel','Cancelled look changed saved character');checks.push('Bat wings and cancellation');
 await evaluate('document.getElementById("world-settings").click();document.querySelectorAll("[data-time]")[3].click();document.getElementById("world-cycle").checked=false;document.getElementById("world-cycle").dispatchEvent(new Event("change"));document.querySelector("[data-weather=snow]").click();document.getElementById("sky-done").click()');await sleep(1700);d=await evaluate('WildwoodDiagnostics()');assert(d.weather.hour===0&&d.weather.weather==='snow'&&d.weather.daylight<.05&&d.weather.weights.snow>.4,'Night or snow failed');await screenshot('snowy-night.png');await call('Page.reload');await sleep(1000);d=await evaluate('WildwoodDiagnostics()');assert(d.state.world.hour===0&&d.state.world.weather==='snow'&&!d.state.world.cycle,'Sky settings not saved');assert(d.ambience.fireflies===32&&d.ambience.flowers===30,'Night ambience missing');await evaluate('document.getElementById("home").click()');await sleep(400);await screenshot('cosy-cottage-night.png');checks.push('Night, snowfall, sky persistence, glowing flowers and fireflies');
 await evaluate('document.getElementById("world-settings").click();document.querySelectorAll("[data-time]")[1].click();document.querySelector("[data-weather=rain]").click();document.getElementById("world-cycle").checked=true;document.getElementById("world-cycle").dispatchEvent(new Event("change"));document.getElementById("world-speed").value=4;document.getElementById("world-speed").dispatchEvent(new Event("input"));document.getElementById("sky-done").click()');await sleep(1800);d=await evaluate('WildwoodDiagnostics()');assert(d.weather.hour>12&&d.weather.weather==='rain'&&d.weather.weights.rain>.4&&d.weather.daylight>.9,'Day cycle or rain failed');checks.push('Day cycle and dynamic rain');
 let s=d.state;s.world={hour:9,cycle:false,speed:1,weather:'auto',autoWeather:'clear',weatherAge:84.95};await reload(s);await sleep(300);assert((await evaluate('WildwoodDiagnostics()')).weather.weather==='cloudy','Automatic weather did not change');checks.push('Automatic weather transition');
 s=(await evaluate('WildwoodDiagnostics()')).state;s.x=21;s.z=12;s.world={hour:10,cycle:false,speed:1,weather:'clear',autoWeather:'clear',weatherAge:0};await reload(s);await key('w',750);d=await evaluate('WildwoodDiagnostics()');assert(d.water.wading&&d.water.splashes>0&&d.water.ripples>0,'Foot splashes failed');await screenshot('shallow-water.png');const steps=d.water.splashes;await key(' ');await sleep(2100);d=await evaluate('WildwoodDiagnostics()');assert(d.water.splashes>steps,'Landing splash failed: '+JSON.stringify(d.water)+' '+JSON.stringify(d.jump));checks.push('Wading, foot splashes, and landing splash');
 s=(await evaluate('WildwoodDiagnostics()')).state;s.x=-15.2;s.z=6;await reload(s);await key('e');assert(await evaluate('!!document.getElementById("rune-poem")&&document.getElementById("rune-poem").textContent.split(String.fromCharCode(10)).length===4'),'Runestone poem failed');await screenshot('runestone-poetry.png');await evaluate('document.getElementById("rune-close").click()');checks.push('Eight runestones and original poetry');
 await evaluate('document.getElementById("home").click()');await sleep(200);await key('e');assert(await evaluate('!!document.getElementById("plant")'),'Den interaction failed');await evaluate('document.getElementById("plant").click()');assert((await evaluate('WildwoodDiagnostics()')).state.visited.includes('den'),'Free den decoration failed');await key('e');await evaluate('document.getElementById("plant").click()');assert(!(await evaluate('WildwoodDiagnostics()')).state.visited.includes('den'),'Den decoration toggle failed');assert(await evaluate('!document.getElementById("leaves")&&!document.getElementById("quest-count")'),'Currency/quest UI remains');assert(!('leaves' in (await evaluate('WildwoodDiagnostics()')).state),'Currency save remains');checks.push('Sandbox without currency and free decoration');
 await evaluate('if(!WildwoodDiagnostics().music.enabled)document.getElementById("sound").click()');await key('m');await sleep(450);assert(!(await evaluate('WildwoodDiagnostics()')).music.enabled,'Music mute failed');await call('Page.reload');await sleep(1000);assert(!(await evaluate('WildwoodDiagnostics()')).music.enabled,'Music mute persistence failed');await evaluate('document.getElementById("sound").click()');await sleep(1600);assert((await evaluate('WildwoodDiagnostics()')).music.state==='running','Music resume failed');checks.push('Offline music and mute persistence');
 s=(await evaluate('WildwoodDiagnostics()')).state;s.x=0;s.z=6;s.world={hour:10,cycle:true,speed:1,weather:'clear',autoWeather:'clear',weatherAge:0};await reload(s);await sleep(1200);await screenshot('sandbox-preview.png');assert(errors.length===0,'Browser exceptions: '+JSON.stringify(errors));assert(external.length===0,'Unexpected network requests');d=await evaluate('WildwoodDiagnostics()');assert(d.webgl===0,'WebGL errors');checks.push('No network requests or browser errors');console.log(JSON.stringify({result:'passed',checks,diagnostics:d},null,2));await call('Browser.close');socket.close();
})().catch(async e=>{console.error(e);try{await call('Browser.close');}catch{}child.kill();process.exitCode=1;});

