const {spawn}=require('node:child_process'),fs=require('node:fs'),M=require('../game/model.js');
const root=process.env.WILDWOOD_ROOT||'D:/AnimalJamOffline/android-build/mobile-test';
const child=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--no-first-run','--remote-debugging-port=9226','--user-data-dir='+root+'/bobo-profile','--use-angle=swiftshader','--enable-unsafe-swiftshader','--window-size=1280,800','about:blank'],{windowsHide:true,stdio:'ignore'});
let ws,id=0;const pending=new Map(),errors=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));function assert(v,m){if(!v)throw Error(m);}
function call(method,params={}){return new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});}
async function ev(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function shot(name){const r=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(root+'/'+name,Buffer.from(r.data,'base64'));}
(async()=>{let tabs;for(let i=0;i<80;i++){try{tabs=await(await fetch('http://127.0.0.1:9226/json')).json();if(tabs.length)break;}catch{}await sleep(150);}assert(tabs?.length,'Browser startup');ws=new WebSocket(tabs[0].webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};await call('Runtime.enable');await call('Page.enable');
const save={...M.fresh(),x:24,z:15,started:true,soul:'frost',world:{hour:10,cycle:false,speed:1,weather:'clear'}};await call('Page.addScriptToEvaluateOnNewDocument',{source:'localStorage.setItem("wildwood-save-v1",'+JSON.stringify(JSON.stringify(save))+')'});await call('Page.navigate',{url:'file:///'+root+'/game/index.html'});for(let i=0;i<80;i++){if(await ev('document.body?.dataset.ready==="true"'))break;await sleep(250);}assert(await ev('document.body?.dataset.ready==="true"'),'Startup failed: '+JSON.stringify(errors));await sleep(300);
let d=await ev('WildwoodDiagnostics()');assert(d.npcs.some(n=>n.name.startsWith('Bobo')&&n.kind==='axolotl'&&n.x===26&&n.z===14),'Bobo NPC missing');assert(d.water.center[0]===21&&d.water.center[1]===12,'Pond center not relocated');assert(await ev('!new ShallowWater().contains(15,5)&&new ShallowWater().contains(21,12)'),'Old pond still wet');assert(await ev('(()=>{const a=BoboPlush.mesh({t:2});return a.length>0&&a.length%9===0&&a.every(Number.isFinite)})()'),'Bobo mesh invalid');
assert(await ev('WildwoodPond.z-WildwoodPond.radius>Math.sin(WildwoodPond.x*.08)*2+2.2'),'Pond overlaps main path');await call('Input.dispatchMouseEvent',{type:'mousePressed',x:200,y:500,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:608,y:500,buttons:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:608,y:500,button:'left',clickCount:1});await sleep(250);await shot('bobo-pond.png');
await call('Input.dispatchKeyEvent',{type:'keyDown',key:'e',code:'KeyE',windowsVirtualKeyCode:69});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'e',code:'KeyE'});await sleep(150);assert(await ev('!!document.getElementById("bobo-done")&&document.getElementById("modal-kicker").textContent.includes("BOBO")'),'Bobo dialogue failed');await shot('bobo-dialog.png');await ev('document.getElementById("bobo-skies").click()');assert(await ev('!!document.getElementById("sky-done")'),'Bobo sky option failed');await ev('document.getElementById("sky-done").click()');
await ev('document.getElementById("pause").click()');await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});const before=await ev('getComputedStyle(document.querySelector(".dialog"),"::after").animationName');assert(before==='moss-sway','Moss animation missing');await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert(await ev('getComputedStyle(document.querySelector(".dialog"),"::after").animationName==="none"'),'Reduced motion ignored');assert(!errors.length,'Browser exceptions '+JSON.stringify(errors));assert((await ev('WildwoodDiagnostics()')).webgl===0,'WebGL error');console.log('PASS: Bobo mesh, shoreline location, interaction and sky dialogue, relocated pond clear of path, moss animation and reduced motion');await call('Browser.close');ws.close();})().catch(async e=>{console.error(e);try{await call('Browser.close');}catch{}child.kill();process.exitCode=1;});


